baseURL = 'https://farhan-muh.github.io/'
languageCode = 'id-id'
title = "Farhan's Note"
theme = "PaperMod"
copyright = "¬© 2026 Muhamad Farhan Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
fuseOpts = { isCaseSensitive = false, shouldSort = true, location = 0, distance = 100, threshold = 0.4, minMatchCharLength = 0, keys = [
    "title",
    "permalink",
    "summary",
    "content",
] }

[params.profileMode]
enabled = true
title = "Halo, saya Farhan!"
subtitle = "Pengajar Digital & Penulis Tutorial. Selamat belajar!"
# imageUrl = "link-foto-kamu.jpg" # Bisa dikosongkan dulu

[[menu.main]]
name = "Tutorial"
url = "/posts/"
weight = 10

[[menu.main]]
name = "üîç Cari"
url = "search"
weight = 20
